= Latin-2-Assignments
:toc: left
:toclevels: 3
:sectids:
:sectlinks:
:sectanchors:
:sectnums:
:sectnumlevels: 2


== 1st Quarter
=== Module 1 -- Review 1
==== Week 1
//tag::Week-1[]
//tag::Weekly-Overview-1[]
July 22-26

There is no "Launch Work."
//end::Weekly-Overview-1[]
//end::Week-1[]

==== Week 2
//tag::Week-2
//tag::Weekly-Overview-2[]
July 29-Aug 2

There is no "Launch Work."
//end::Weekly-Overview-2[]
//end::Week-2[]

==== Week 3
//tag::Week-3[]
Chapters 1-4

1. 1st declension
2. singular vs plural nouns and verbs
3. 2nd declension
4. Accusative and DO

//tag::Weekly-Overview-3[]
Aug 5-Aug 9

We will begin to review material from Latin 1.

We will review the Nominative and Accusative cases as well as third person verbs.

//end::Weekly-Overview-3[]
//tag::Assignment-001[]
===== Monday, August 5, 2024
No work

//end::Assignment-001[]
//tag::Assignment-002[]
===== Tuesday, August 6, 2024
We covered the syllabus and discussed homework for the week.

We translated the story for chapter 1 in class and began the story for chapter 2.

//end::Assignment-002[]
//tag::Assignment-003[]
===== Wednesday, August 7, 2024
Finish the story for chapter 2.

Be mindful of noun and verb endings.

Review vocabulary.
 
//end::Assignment-003[]
//tag::Assignment-004[]
===== Thursday, August 8, 2024
Translate the story for chapter 3.

Be mindful of noun and verb endings.

Upload the translations from chapters 2 and 3.

Review vocabulary.

//end::Assignment-004[]
//tag::Assignment-005[]
===== Friday, August 9, 2024
We will review the translations for chapters 2 and 3.

We will translate the story for chapter 4.

We will talk about the quiz on Tuesday.

//end::Assignment-005[]
Play kahoot?
Go over website?

//end::Week-3[]
==== Week 4
//tag::Week-4[]
Chapter 5 Infinitive and Aeneas

Chapter 6 Infinitives, gender agreement, and The Slave Market

Chapter 7 3rd Declension, plural accusatives, and Latin Villa. 

7.1 Review section - Aeneas Leaves Troy

//tag::Weekly-Overview-4[]
We will review infinitives, gender agreement, and the 3rd Declension.


//end::Weekly-Overview-4[]
//tag::Assignment-006[]
===== Monday, August 12, 2024
Upload the translation for chapter 4.

Study for Quiz

If the links do not work, try right-clicking them and opening them in a new tab.

https://drive.google.com/file/d/1Ok26OVnaYDAuHeV0WaSjnEWD8iHvu4FF/view?usp=share_link[Vocabulary for Chapters 1-4]

https://drive.google.com/file/d/1Ok26OVnaYDAuHeV0WaSjnEWD8iHvu4FF/view?usp=share_link[Stories for Chapters 1-4]

http://joshualbogle.com[Review Stories from Textbook]



//end::Assignment-006[]
//tag::Quiz-01[]
We will have a quiz over vocabulary, nominatives, accusatives, and 3rd person verb endings.

//end::Quiz-01[]
//tag::Assignment-007[]
===== Tuesday, August 13, 2024

We will begin reviewing infinitives, gender agreement, and the 3rd Declension.

We will translate the story for chapter 5.

https://drive.google.com/file/d/1RaAToSKcq5VfdPqNPceX9zKex_twEVIT/view?usp=share_link[Stories from Chapters 5-7]

https://drive.google.com/file/d/1RaLVFK3XMcZjtTmFVh_c4DSSjymNiWEM/view?usp=share_link[Vocabulary for Chapters 5-7]


//end::Assignment-007[]
//tag::Assignment-008[]
===== Wednesday, August 14, 2024
Review https://drive.google.com/file/d/1RaLVFK3XMcZjtTmFVh_c4DSSjymNiWEM/view?usp=share_link[Vocabulary for Chapters 5-7]

Translate the story for chapter 6.
https://drive.google.com/file/d/1RaAToSKcq5VfdPqNPceX9zKex_twEVIT/view?usp=share_link[Stories from Chapters 5-7]

http://joshualbogle.com[Review Stories from Textbook]


//end::Assignment-008[]
//tag::Assignment-009[]
===== Thursday, August 15, 2024
Review https://drive.google.com/file/d/1RaLVFK3XMcZjtTmFVh_c4DSSjymNiWEM/view?usp=share_link[Vocabulary for Chapters 5-7]

Translate the story for chapter 7.
https://drive.google.com/file/d/1RaAToSKcq5VfdPqNPceX9zKex_twEVIT/view?usp=share_link[Stories from Chapters 5-7]

http://joshualbogle.com[Review Stories from Textbook]

Upload the translations for chapter 5, 6, and 7.

//end::Assignment-009[]
//tag::Assignment-010[]
===== Friday, August 16, 2024
We will review the translations from chapters 6 and 7.

We will translate the story for chapter 8.
https://drive.google.com/file/d/1RhP3riEFNa6vnz6Plk-9k3GgOKmLLmf0/view?usp=share_link[Chapter 8 and 9]

//end::Assignment-010[]

//tag::Quiz-02[]
We will have a quiz over vocabulary, infinitives, gender agreement, and the nominative and accussative cases. This will include the 1st, 2nd, and 3rd declensions.

https://drive.google.com/file/d/1RaLVFK3XMcZjtTmFVh_c4DSSjymNiWEM/view?usp=share_link[Vocabulary for Chapters 5-7]

https://drive.google.com/file/d/1RaAToSKcq5VfdPqNPceX9zKex_twEVIT/view?usp=share_link[Stories from Chapters 5-7]

http://joshualbogle.com[Review Stories from Textbook]

//end::Quiz-02[]
//end::Week-4[]

==== Week 5
//tag::Week-5[]
Chapter 8 Verbs - Person, Patria Potestas

Chapter 9 Ablatives, gods and goddesses

Chapter 10 Conjugations, Imperatives, Treatment of Slaves

Chapter 11 Genitive, Roman Names, and The Founding of Rome

Chapter 12 Ablatives time when, time within which, what instrument, by what means, how, in what manner 

12.1 On the banks of the Tiber

//tag::Weekly-Overview-5[]
We will review peronal verb endings, ablatives, and genitives.

//end::Weekly-Overview-5[]

//tag::Assignment-011[]
===== Monday, August 19, 2024
Study 
https://drive.google.com/file/d/1Rhb2GS2su62c9scEnUY6yFVh2DAuw8JO/view?usp=share_link[Chapter 8 and 9 Vocabulary]

Translate the story for chapter 9.
https://drive.google.com/file/d/1RhP3riEFNa6vnz6Plk-9k3GgOKmLLmf0/view?usp=share_link[Chapter 8 and 9 Story]

Upload the translations for chapters 8 and 9.

//end::Assignment-011[]
//tag::Assignment-012[]
===== Tuesday, August 20, 2024
We will review the translation for chapter 9.

We will translate the story for chapter 10

//end::Assignment-012[]
//tag::Assignment-013[]
===== Wednesday, August 21, 2024
Translate the story for chapter 11.
https://drive.google.com/file/d/1RjY7fZSU3xyHI6dhh8oZ3nHrp4omDR94/view?usp=share_link[Chapter 10-12 Story]

Study 
https://drive.google.com/file/d/1Rhb2GS2su62c9scEnUY6yFVh2DAuw8JO/view?usp=share_link[Chapter 8 and 9 Vocabulary]
and
https://drive.google.com/file/d/1RlK01qXR9NXhLE1tfDr_6xAU5VQD96pI/view?usp=share_link[Chapter 10-12 Vocabulary]

//end::Assignment-013[]
//tag::Assignment-014[]
===== Thursday, August 22, 2024
Translate the story for chapter 12.
https://drive.google.com/file/d/1RjY7fZSU3xyHI6dhh8oZ3nHrp4omDR94/view?usp=share_link[Chapter 10-12 Story]

Upload the translations for chapters 10, 11, and 12.


Study 
https://drive.google.com/file/d/1Rhb2GS2su62c9scEnUY6yFVh2DAuw8JO/view?usp=share_link[Chapter 8 and 9 Vocabulary]
and 
https://drive.google.com/file/d/1RlK01qXR9NXhLE1tfDr_6xAU5VQD96pI/view?usp=share_link[Chapter 10-12 Vocabulary]



//end::Assignment-014[]
//tag::Assignment-015[]
===== Friday, August 23, 2024
We will review the translations for chapters 11 and 12.

We will translate chapter 13 in class. https://drive.google.com/file/d/1RsxHQDqZ-xcWDvpEHQjamwAtgh5c4BDD/view?usp=share_link[Chapter 13-17 Stories]

//end::Assignment-015[]
//tag::Quiz-03[]
We will have a quiz over the vocabulary for chapters 8-12, personal verb endings, imperatives, ablatives, and genitives. 

//end::Quiz-03[]
//end::Week-5[]


==== Week 6
//tag::Week-6[]
Chaptes 13-17

13. 3rd i-stem, Imperfect, Adverb
14. Imperfect, irregular verbs, The Kings of Rome.
15. Neuter, Roman Numerals, numbers.
16. Noun/adjective agreement, numbers.
17. Irr. Verbs Review
17.1 Roman Influence in the East

//tag::Weekly-Overview-6[]
We will review the Imperfect verb forms, 1st-3rd declensions, and noun/adjective agreement.

//end::Weekly-Overview-6[]
//tag::Assignment-016[]
===== Monday, August 26, 2024
Study Vocabulary. https://drive.google.com/file/d/1RzNbrB7EHVARoIegWjguMzsuvrxhRvuf/view?usp=sharing[Chapter 13-17 Vocabulary]

Translate Chapter 14. https://drive.google.com/file/d/1RsxHQDqZ-xcWDvpEHQjamwAtgh5c4BDD/view?usp=share_link[Chapter 13-17 Stories]

Submit Chapters 13 and 14.

//end::Assignment-016[]
//tag::Assignment-017[]
===== Tuesday, August 27, 2024
We will translate chapter 15. https://drive.google.com/file/d/1RsxHQDqZ-xcWDvpEHQjamwAtgh5c4BDD/view?usp=share_link[Chapter 13-17 Stories]

//end::Assignment-017[]
//tag::Assignment-018[]
===== Wednesday, August 28, 2024
Study Vocabulary. https://drive.google.com/file/d/1RzNbrB7EHVARoIegWjguMzsuvrxhRvuf/view?usp=sharing[Chapter 13-17 Vocabulary]

Translate chapter 16. https://drive.google.com/file/d/1RsxHQDqZ-xcWDvpEHQjamwAtgh5c4BDD/view?usp=share_link[Chapter 13-17 Stories]

//end::Assignment-018[]
//tag::Assignment-019[]
===== Thursday, August 29, 2024
Study Vocabulary. https://drive.google.com/file/d/1RzNbrB7EHVARoIegWjguMzsuvrxhRvuf/view?usp=sharing[Chapter 13-17 Vocabulary]

Translate chapter 17. https://drive.google.com/file/d/1RsxHQDqZ-xcWDvpEHQjamwAtgh5c4BDD/view?usp=share_link[Chapter 13-17 Stories]

Submit chapters 15-17.

//end::Assignment-019[]
//tag::Assignment-020[]
===== Friday, August 30, 2024

//end::Assignment-020[]
//tag::Quiz-04[]
Quiz over the vocabulary for chapters 13-17, imperfect verbs, 1st-3rd declension nouns, and adjective agreement.

//end::Quiz-04[]
//end::Week-6[]

==== Week 7
//tag::Week-7[]
Chapters 1-17

//tag::Weekly-Overview-7[]
We will have our first test over chapters 1-17.

//end::Weekly-Overview-7[]
//tag::Assignment-021[]
===== Monday, September 2, 2024
*Labor Day*

//end::Assignment-021[]
//tag::Assignment-022[]
===== Tuesday, September 3, 2024
*Satellite Day*
Study materials 

http://joshualbogle.com[Review Stories from Textbook]

https://drive.google.com/file/d/1Ok26OVnaYDAuHeV0WaSjnEWD8iHvu4FF/view?usp=share_link[Vocabulary for Chapters 1-4]

https://drive.google.com/file/d/1Ok26OVnaYDAuHeV0WaSjnEWD8iHvu4FF/view?usp=share_link[Stories for Chapters 1-4]

https://drive.google.com/file/d/1RaLVFK3XMcZjtTmFVh_c4DSSjymNiWEM/view?usp=share_link[Vocabulary for Chapters 5-7]

https://drive.google.com/file/d/1RaAToSKcq5VfdPqNPceX9zKex_twEVIT/view?usp=share_link[Stories from Chapters 5-7]

https://drive.google.com/file/d/1Rhb2GS2su62c9scEnUY6yFVh2DAuw8JO/view?usp=share_link[Chapter 8 and 9 Vocabulary]

https://drive.google.com/file/d/1RhP3riEFNa6vnz6Plk-9k3GgOKmLLmf0/view?usp=share_link[Chapter 8 and 9 Story]

https://drive.google.com/file/d/1RlK01qXR9NXhLE1tfDr_6xAU5VQD96pI/view?usp=share_link[Chapter 10-12 Vocabulary]

https://drive.google.com/file/d/1RjY7fZSU3xyHI6dhh8oZ3nHrp4omDR94/view?usp=share_link[Chapter 10-12 Story]

https://drive.google.com/file/d/1RzNbrB7EHVARoIegWjguMzsuvrxhRvuf/view?usp=sharing[Chapter 13-17 Vocabulary]

https://drive.google.com/file/d/1RsxHQDqZ-xcWDvpEHQjamwAtgh5c4BDD/view?usp=share_link[Chapter 13-17 Stories]


//end::Assignment-022[]
//tag::Assignment-023[]
===== Wednesday, September 4, 2024

Study materials 

http://joshualbogle.com[Review Stories from Textbook]

https://drive.google.com/file/d/1Ok26OVnaYDAuHeV0WaSjnEWD8iHvu4FF/view?usp=share_link[Vocabulary for Chapters 1-4]

https://drive.google.com/file/d/1Ok26OVnaYDAuHeV0WaSjnEWD8iHvu4FF/view?usp=share_link[Stories for Chapters 1-4]

https://drive.google.com/file/d/1RaLVFK3XMcZjtTmFVh_c4DSSjymNiWEM/view?usp=share_link[Vocabulary for Chapters 5-7]

https://drive.google.com/file/d/1RaAToSKcq5VfdPqNPceX9zKex_twEVIT/view?usp=share_link[Stories from Chapters 5-7]

https://drive.google.com/file/d/1Rhb2GS2su62c9scEnUY6yFVh2DAuw8JO/view?usp=share_link[Chapter 8 and 9 Vocabulary]

https://drive.google.com/file/d/1RhP3riEFNa6vnz6Plk-9k3GgOKmLLmf0/view?usp=share_link[Chapter 8 and 9 Story]

https://drive.google.com/file/d/1RlK01qXR9NXhLE1tfDr_6xAU5VQD96pI/view?usp=share_link[Chapter 10-12 Vocabulary]

https://drive.google.com/file/d/1RjY7fZSU3xyHI6dhh8oZ3nHrp4omDR94/view?usp=share_link[Chapter 10-12 Story]

https://drive.google.com/file/d/1RzNbrB7EHVARoIegWjguMzsuvrxhRvuf/view?usp=sharing[Chapter 13-17 Vocabulary]

https://drive.google.com/file/d/1RsxHQDqZ-xcWDvpEHQjamwAtgh5c4BDD/view?usp=share_link[Chapter 13-17 Stories]


//end::Assignment-023[]
//tag::Assignment-024[]
===== Thursday, September 5, 2024
Study materials 

http://joshualbogle.com[Review Stories from Textbook]

https://drive.google.com/file/d/1Ok26OVnaYDAuHeV0WaSjnEWD8iHvu4FF/view?usp=share_link[Vocabulary for Chapters 1-4]

https://drive.google.com/file/d/1Ok26OVnaYDAuHeV0WaSjnEWD8iHvu4FF/view?usp=share_link[Stories for Chapters 1-4]

https://drive.google.com/file/d/1RaLVFK3XMcZjtTmFVh_c4DSSjymNiWEM/view?usp=share_link[Vocabulary for Chapters 5-7]

https://drive.google.com/file/d/1RaAToSKcq5VfdPqNPceX9zKex_twEVIT/view?usp=share_link[Stories from Chapters 5-7]

https://drive.google.com/file/d/1Rhb2GS2su62c9scEnUY6yFVh2DAuw8JO/view?usp=share_link[Chapter 8 and 9 Vocabulary]

https://drive.google.com/file/d/1RhP3riEFNa6vnz6Plk-9k3GgOKmLLmf0/view?usp=share_link[Chapter 8 and 9 Story]

https://drive.google.com/file/d/1RlK01qXR9NXhLE1tfDr_6xAU5VQD96pI/view?usp=share_link[Chapter 10-12 Vocabulary]

https://drive.google.com/file/d/1RjY7fZSU3xyHI6dhh8oZ3nHrp4omDR94/view?usp=share_link[Chapter 10-12 Story]

https://drive.google.com/file/d/1RzNbrB7EHVARoIegWjguMzsuvrxhRvuf/view?usp=sharing[Chapter 13-17 Vocabulary]

https://drive.google.com/file/d/1RsxHQDqZ-xcWDvpEHQjamwAtgh5c4BDD/view?usp=share_link[Chapter 13-17 Stories]

//end::Assignment-024[]
//tag::Assignment-025[]
===== Friday, September 6, 2024

//end::Assignment-025[]
//tag::Test-01[]
This test will cover vocabulary for chapters 1-17, the verb endings we have covered, and the noun/adjective endings we have covered.

//end::Test-01[]
//end::Week-7[]

=== Module 2 -- Review 2
==== Week 8
//tag::Week-8[]
Chapters 18-21

18. 3rd declension adjectives, horatius, Mucius Scaevola, Cloelia, Cincinnatus
19. Perfect Tense, Horace's Journey
20. Perfect Tense, Subordinate Clauses with Dum, Infinitive Review
21.

//tag::Weekly-Overview-8[]
We will study 3rd declension adjectives and the perfect tense.

//end::Weekly-Overview-8[]
//tag::Assignment-026[]
===== Monday, September 9, 2024
Translate and submit the story for 
https://drive.google.com/file/d/1Q5ijhrNRoBvyhod3AdbQBIIYaNFI7qJG/view?usp=sharing[chapter 18]. 

Review https://drive.google.com/file/d/1mM9GKfoezzPprVOJh-FSW-qnKdHHg6HU/view?usp=sharing[Vocabulary for Chapters 18-21]

//end::Assignment-026[]
//tag::Assignment-027[]
===== Tuesday, September 10, 2024
Translate the story for 
https://drive.google.com/file/d/1Q5ijhrNRoBvyhod3AdbQBIIYaNFI7qJG/view?usp=sharing[chapter 19].

//end::Assignment-027[]
//tag::Assignment-028[]
===== Wednesday, September 11, 2024
Translate the story for 
https://drive.google.com/file/d/1Q5ijhrNRoBvyhod3AdbQBIIYaNFI7qJG/view?usp=sharing[chapter 20]. 

Review https://drive.google.com/file/d/1mM9GKfoezzPprVOJh-FSW-qnKdHHg6HU/view?usp=sharing[Vocabulary for Chapters 18-21]

//end::Assignment-028[]
//tag::Assignment-029[]
===== Thursday, September 12, 2024
Translate the story for 
https://drive.google.com/file/d/1Q5ijhrNRoBvyhod3AdbQBIIYaNFI7qJG/view?usp=sharing[chapter 21]. 

Submit chapters 19-21.

Review https://drive.google.com/file/d/1mM9GKfoezzPprVOJh-FSW-qnKdHHg6HU/view?usp=sharing[Vocabulary for Chapters 18-21]

//end::Assignment-029[]
//tag::Assignment-030[]
===== Friday, September 13, 2024

We will review the dative case and future tense.

We will translate 
https://drive.google.com/file/d/1uwgiq1Ayd-Gi7GMZ7B1O_KsJXjZwY244/view?usp=share_link[Chapter 22].

//end::Assignment-030[]
//tag::Quiz-05[]
Quiz over chapters 18-21.

//end::Quiz-05[]
//end::Week-8[]


==== Week 9
//tag::Week-9[]
Chapters 22-24

//tag::Weekly-Overview-9[]
We will learn about the dative case and distinguishing them from ablatives. We will also learn the future tense.

//end::Weekly-Overview-9[]
//tag::Assignment-031[]
===== Monday, September 16, 2024
Study 
https://drive.google.com/file/d/1uwgiq1Ayd-Gi7GMZ7B1O_KsJXjZwY244/view?usp=share_link[Vocabulary for Chapters 22-24]

Translate and submit the first 2 pages of 
https://drive.google.com/file/d/1uwgiq1Ayd-Gi7GMZ7B1O_KsJXjZwY244/view?usp=share_link[chapter 22].


//end::Assignment-031[]
//tag::Assignment-032[]
===== Tuesday, September 17, 2024
*Chapel Day*

We will review the dative case and future tense. Then we will translate 
https://drive.google.com/file/d/1uwgiq1Ayd-Gi7GMZ7B1O_KsJXjZwY244/view?usp=share_link[chapter 23].

//end::Assignment-032[]
//tag::Assignment-033[]
===== Wednesday, September 18, 2024
Translate 
https://drive.google.com/file/d/1uwgiq1Ayd-Gi7GMZ7B1O_KsJXjZwY244/view?usp=share_link[chapter 24].

Review
https://drive.google.com/file/d/109tU1ll6pkNODQFidRgchNe6v37KvuyC/view?usp=share_link[Person and Number Notes]

//end::Assignment-033[]
//tag::Assignment-034[]
===== Thursday, September 19, 2024
Review the vocabulary and grammar for chapters 22-24.

https://drive.google.com/file/d/1uwgiq1Ayd-Gi7GMZ7B1O_KsJXjZwY244/view?usp=share_link[Vocabulary for Chapters 22-24]

https://drive.google.com/file/d/109tU1ll6pkNODQFidRgchNe6v37KvuyC/view?usp=share_link[Person and Number Notes]

Submit your translations for 
https://drive.google.com/file/d/1uwgiq1Ayd-Gi7GMZ7B1O_KsJXjZwY244/view?usp=share_link[chapters 23 and 24].

//end::Assignment-034[]
//tag::Assignment-035[]
===== Friday, September 20, 2024


//end::Assignment-035[]
//tag::Quiz-06[]
We will have a quiz over the vocabulary and grammar for chapters 22-24.

This will cover the present, imperfect, future, and perfect tenses. We will cover the dative case in another quiz.

//end::Quiz-06[]
//end::Week-9[]

==== Week 10
//tag::Week-10[]
Chapters 18-27

//tag::Weekly-Overview-10[]
10

//end::Weekly-Overview-10[]
//end::Week-10[]

==== Week 11
//tag::Week-11[]
//tag::Weekly-Overview-11[]
11

//end::Weekly-Overview-11[]
//tag::Assignment-036[]
===== Monday, September 30, 2024
Review
https://drive.google.com/file/d/109tU1ll6pkNODQFidRgchNe6v37KvuyC/view?usp=share_link[Person and Number Notes]

https://drive.google.com/file/d/1Q5ijhrNRoBvyhod3AdbQBIIYaNFI7qJG/view?usp=sharing[chapters 18-21].

https://drive.google.com/file/d/1uwgiq1Ayd-Gi7GMZ7B1O_KsJXjZwY244/view?usp=share_link[chapters 22-24].
//end::Assignment-036[]
//tag::Assignment-037[]
===== Tuesday, October 1, 2024

//end::Assignment-037[]
//tag::Assignment-038[]
===== Wednesday, October 2, 2024
Finish the https://drive.google.com/file/d/1k90cSbXq7RZ6XWMcUAz9g0LnQ1e-kUTq/view?usp=share_link[translation].

Review
https://drive.google.com/file/d/109tU1ll6pkNODQFidRgchNe6v37KvuyC/view?usp=share_link[Person and Number Notes]

https://drive.google.com/file/d/1Q5ijhrNRoBvyhod3AdbQBIIYaNFI7qJG/view?usp=sharing[chapters 18-21].

https://drive.google.com/file/d/1uwgiq1Ayd-Gi7GMZ7B1O_KsJXjZwY244/view?usp=share_link[chapters 22-24].

//end::Assignment-038[]
//tag::Assignment-039[]
===== Thursday, October 3, 2024

Submit the 
https://drive.google.com/file/d/1k90cSbXq7RZ6XWMcUAz9g0LnQ1e-kUTq/view?usp=share_link[translation].

Review
https://drive.google.com/file/d/109tU1ll6pkNODQFidRgchNe6v37KvuyC/view?usp=share_link[Person and Number Notes]

https://drive.google.com/file/d/1Q5ijhrNRoBvyhod3AdbQBIIYaNFI7qJG/view?usp=sharing[chapters 18-21].

https://drive.google.com/file/d/1uwgiq1Ayd-Gi7GMZ7B1O_KsJXjZwY244/view?usp=share_link[chapters 22-24].

//end::Assignment-039[]
//tag::Assignment-040[]
===== Friday, October 4, 2024

//end::Assignment-040[]
//tag::Test-02[]
The test will cover vocabulary from chapers 18-24. It will cover all six verb tenses as well as person and number. There will be some questions over the 1st, 2nd, and 3rd declensions. 

//end::Test-02[]

//end::Week-11[]


== 2nd Quarter
=== Module 3 -- Chapters 28-30

==== Week 12
//tag::Week-12[]
//tag::Weekly-Overview-12[]
We will study nouns, pronouns, and adjectives including the 4th and 5th declension, hic, and ille.

//end::Weekly-Overview-12[]

//tag::Assignment-041[]
===== Monday, October 7, 2024
Complete the first page of 
https://drive.google.com/file/d/1thYgm2_9SlfnY7H8kwA4_9Cd30SNSQ6U/view?usp=share_link[Chapters 25-27]

//end::Assignment-041[]
//tag::Assignment-042[]
===== Tuesday, October 8, 2024
We translated 
https://drive.google.com/file/d/1thYgm2_9SlfnY7H8kwA4_9Cd30SNSQ6U/view?usp=share_link[Chapters 25]
in class.

//end::Assignment-042[]
//tag::Assignment-043[]
===== Wednesday, October 9, 2024
Finish 
https://drive.google.com/file/d/1thYgm2_9SlfnY7H8kwA4_9Cd30SNSQ6U/view?usp=share_link[Chapters 25 and 26]

Review https://drive.google.com/file/d/1fJhECWRtztacNRoBbpL0e8PEpSZHdaHp/view?usp=share_link[Vocabulary for Chapters 25 and 26]

Sample quiz questions

What is the case of nōmen?

What is the gender and number of nōmen?

What is the best translation of hic?

A) this man
B) these men
C) that man
D) those men

//end::Assignment-043[]
//tag::Assignment-044[]
===== Thursday, October 10, 2024
Submit
https://drive.google.com/file/d/1thYgm2_9SlfnY7H8kwA4_9Cd30SNSQ6U/view?usp=share_link[Chapters 25 and 26]

Review https://drive.google.com/file/d/1fJhECWRtztacNRoBbpL0e8PEpSZHdaHp/view?usp=share_link[Vocabulary for Chapters 25 and 26]

Sample quiz questions

What is the case of nōmen?

What is the gender and number of nōmen?

What is the best translation of hic?

A) this man
B) these men
C) that man
D) those men

//end::Assignment-044[]
//tag::Assignment-045[]
===== Friday, October 11, 2024



//end::Assignment-045[]
//tag::Quiz-07[]
We will have a quiz over the 
https://drive.google.com/file/d/1fJhECWRtztacNRoBbpL0e8PEpSZHdaHp/view?usp=share_link[Vocabulary for chapters 25 and 26] and grammar for chapters 25-26.

The grammar will focus on nouns, pronouns, and adjectives including the 4th and 5th declension, hic, and ille.

Sample quiz questions

What is the case of nōmen?

What is the gender and number of nōmen?

What is the best translation of hic?

A) this man
B) these men
C) that man
D) those men


//end::Quiz-07[]
//end::Week-12[]

==== Week 13
//tag::Week-13[]
//tag::Weekly-Overview-13[]
We will learn about personal pronouns, possive adjectives, and relative pronouns.

//end::Weekly-Overview-13[]
//tag::Assignment-046[]
===== Monday, October 14, 2024

Translate and submit
https://drive.google.com/file/d/1thYgm2_9SlfnY7H8kwA4_9Cd30SNSQ6U/view?usp=share_link[Chapter 27]

Study
https://drive.google.com/file/d/1fJhECWRtztacNRoBbpL0e8PEpSZHdaHp/view?usp=share_link[Chapter 27 Vocabulary]
and
https://drive.google.com/file/d/10agcDfbaLjHG26e-hdRzLdxEYvH8ZRas/view?usp=share_link[Chapter 28 Vocabulary]

//end::Assignment-046[]
//tag::Assignment-047[]
===== Tuesday, October 15, 2024


//end::Assignment-047[]
//tag::Assignment-048[]
===== Wednesday, October 16, 2024

Translate https://drive.google.com/file/d/10gmC0zWq-lXJa8I_OpEgeBTIOqEeLoMZ/view?usp=share_link[Chapter 28].

Study
https://drive.google.com/file/d/1fJhECWRtztacNRoBbpL0e8PEpSZHdaHp/view?usp=share_link[Chapter 27 Vocabulary]
and
https://drive.google.com/file/d/10agcDfbaLjHG26e-hdRzLdxEYvH8ZRas/view?usp=share_link[Chapter 28 Vocabulary]

//end::Assignment-048[]
//tag::Assignment-049[]
===== Thursday, October 17, 2024
Submit https://drive.google.com/file/d/10gmC0zWq-lXJa8I_OpEgeBTIOqEeLoMZ/view?usp=share_link[Chapter 28].


Study
https://drive.google.com/file/d/1fJhECWRtztacNRoBbpL0e8PEpSZHdaHp/view?usp=share_link[Chapter 27 Vocabulary]
and
https://drive.google.com/file/d/10agcDfbaLjHG26e-hdRzLdxEYvH8ZRas/view?usp=share_link[Chapter 28 Vocabulary]

//end::Assignment-049[]
//tag::Assignment-050[]
===== Friday, October 18, 2024

//end::Assignment-050[]
//tag::Quiz-08[]
We will have a quiz over chapters 27-28 vocabulary, personal pronouns and relative pronouns.

//end::Quiz-08[]
//end::Week-13[]

==== Week 14
//tag::Week-14[]
//tag::Weekly-Overview-14[]
We are learning more qu- words and reviewing old ones.

//end::Weekly-Overview-14[]
//tag::Assignment-051[]
===== Monday, October 21, 2024
Finish translating https://drive.google.com/file/d/13X9QXqWn6wNz-Eo5PhKl487EFty6e47x/view?usp=share_link[Chapter 29 Story]

Study https://drive.google.com/file/d/13Y9vr7FzjH3uiKXoOeJYLoCGa7S7bhZB/view?usp=share_link[Chapter 29 Vocabulary]

//end::Assignment-051[]
//tag::Assignment-052[]
===== Tuesday, October 22, 2024
*Seminar Day*

For 29c give the gender, number, and case of relative pronouns.
For 29d give the correct form of the relative pronoun.

//end::Assignment-052[]
//tag::Assignment-053[]
===== Wednesday, October 23, 2024
For 29e follow the instructions to identify the type of qu- word.

Translate the sentences of 29e.

Study
https://drive.google.com/file/d/13Y9vr7FzjH3uiKXoOeJYLoCGa7S7bhZB/view?usp=share_link[Chapter 29 Vocabulary]


//end::Assignment-053[]
//tag::Assignment-054[]
===== Thursday, October 24, 2024
Submit 29c, d, and e.

Study
https://drive.google.com/file/d/13Y9vr7FzjH3uiKXoOeJYLoCGa7S7bhZB/view?usp=share_link[Chapter 29 Vocabulary]


//end::Assignment-054[]
//tag::Assignment-055[]
===== Friday, October 25, 2024

//end::Assignment-055[]
//tag::Quiz-09[]
We will have a quiz over vocabulary and qu- words.

//end::Quiz-09[]
//end::Week-14[]


==== Week 15
//tag::Week-15[]
//tag::Weekly-Overview-15[]
We will continue learning vocabulary.

//end::Weekly-Overview-15[]

//tag::Assignment-056[]
===== Monday, October 28, 2024

Translate and upload pages 1 and 2 of the translation.

Study https://drive.google.com/file/d/1BgBGPkIh1mUIV7af6sQPj3IJvT-wOwlX/view?usp=sharing[Chapter 30 Vocabulary]

//end::Assignment-056[]
//tag::Assignment-057[]
===== Tuesday, October 29, 2024

//end::Assignment-057[]
//tag::Assignment-058[]
===== Wednesday, October 30, 2024

Complete the worksheet for
https://drive.google.com/open?id=16GQqDX7d1fD0zfi-kl9AiIaxn7Oa2ECQ&usp=drive_fs[30b].

Study https://drive.google.com/file/d/1BgBGPkIh1mUIV7af6sQPj3IJvT-wOwlX/view?usp=sharing[Chapter 30 Vocabulary]

//end::Assignment-058[]
//tag::Assignment-059[]
===== Thursday, October 31, 2024
Upload the worksheet for
https://drive.google.com/open?id=16GQqDX7d1fD0zfi-kl9AiIaxn7Oa2ECQ&usp=drive_fs[30b].

Study https://drive.google.com/file/d/1BgBGPkIh1mUIV7af6sQPj3IJvT-wOwlX/view?usp=sharing[Chapter 30 Vocabulary]

//end::Assignment-059[]
//tag::Assignment-060[]
===== Friday, November 1, 2024

//end::Assignment-060[]
//tag::Quiz-10[]
Quiz 10

//end::Quiz-10[]
//end::Week-15[]

==== Week 16
//tag::Week-16[]
//tag::Weekly-Overview-16[]
16

//end::Weekly-Overview-16[]

//tag::Assignment-061[]
===== Monday, November 4, 2024

Complete 30c and 29h.

//end::Assignment-061[]
//tag::Assignment-062[]
===== Tuesday, November 5, 2024
*Satellite Day*

Upload 30c and 29h.

//end::Assignment-062[]
//tag::Assignment-063[]
===== Wednesday, November 6, 2024

Study for your test over chapters 27-30.

//end::Assignment-063[]
//tag::Assignment-064[]
===== Thursday, November 7, 2024

Study for your test over chapters 27-30.

//end::Assignment-064[]
//tag::Assignment-065[]
===== Friday, November 8, 2024

//end::Assignment-065[]
//tag::Test-03[]


Test over chapters 27-30.

//end::Test-03[]
//end::Week-16[]


=== Module 4 -- Chapters 31-32

==== Week 17
//tag::Week-17[]
//tag::Weekly-Overview-17[]
17

//end::Weekly-Overview-17[]

//tag::Assignment-066[]
===== Monday, November 11, 2024

Complete and upload the first page 
https://drive.google.com/open?id=16oeSzjKj6hqqSUI8o3pgC6F4LIEKAWLq&usp=drive_fs[Chapter 31 Story]

Study 
https://drive.google.com/open?id=15Sbic1JNBe47X5Dfusk-tbNppIhKTpdg&usp=drive_fs[Chapter 31 Vocabulary]
//end::Assignment-066[]
//tag::Assignment-067[]
===== Tuesday, November 12, 2024

We finished 
https://drive.google.com/open?id=16oeSzjKj6hqqSUI8o3pgC6F4LIEKAWLq&usp=drive_fs[Chapter 31 Story] in class.

https://drive.google.com/file/d/19YQy6s0JqhEXLyX8PDoRkJ-Frz46JgmD/view?usp=sharing[Translation]

//end::Assignment-067[]
//tag::Assignment-068[]
===== Wednesday, November 13, 2024

Complete 31c on page 34 by writing the correct word. Then Translate the sentence.

// Complete 31d on page 35 by writing the correct word. Then Translate the sentence.

Study 
https://drive.google.com/open?id=15Sbic1JNBe47X5Dfusk-tbNppIhKTpdg&usp=drive_fs[Chapter 31 Vocabulary]

//end::Assignment-068[]
//tag::Assignment-069[]
===== Thursday, November 14, 2024

Submit 31c 
// and 31d.

Study 
https://drive.google.com/open?id=15Sbic1JNBe47X5Dfusk-tbNppIhKTpdg&usp=drive_fs[Chapter 31 Vocabulary]

//end::Assignment-069[]
//tag::Assignment-070[]
===== Friday, November 15, 2024

//end::Assignment-070[]
//tag::Quiz-11[]
Quiz 11

//end::Quiz-11[]
//end::Week-17[]

==== Week 18
//tag::Week-18[]
//tag::Weekly-Overview-18[]
18

//end::Weekly-Overview-18[]

//tag::Assignment-071[]
===== Monday, November 18, 2024

Translate and upload the first page of 
https://drive.google.com/open?id=19jkrX5gar-sDMBCBQeRMY2_TDAbbrzyI&usp=drive_fs[Chapter 32 Story]

Study 
https://drive.google.com/file/d/15uvTXkiCoT7mx8gSwz6HuonUItohLL_X/view?usp=sharing[Chapter 32 Vocabulary]

//end::Assignment-071[]
//tag::Assignment-072[]
===== Tuesday, November 19, 2024
*Chapel Day*

//end::Assignment-072[]
//tag::Assignment-073[]
===== Wednesday, November 20, 2024
Translate the rest of 
https://drive.google.com/open?id=19jkrX5gar-sDMBCBQeRMY2_TDAbbrzyI&usp=drive_fs[Chapter 32 Story]

Study 
https://drive.google.com/file/d/15uvTXkiCoT7mx8gSwz6HuonUItohLL_X/view?usp=sharing[Chapter 32 Vocabulary]

//end::Assignment-073[]
//tag::Assignment-074[]
===== Thursday, November 21, 2024
Upload
https://drive.google.com/open?id=19jkrX5gar-sDMBCBQeRMY2_TDAbbrzyI&usp=drive_fs[Chapter 32 Story]

Study 
https://drive.google.com/file/d/15uvTXkiCoT7mx8gSwz6HuonUItohLL_X/view?usp=sharing[Chapter 32 Vocabulary]
//end::Assignment-074[]
//tag::Assignment-075[]
===== Friday, November 22, 2024

We completed 32b in class.

//end::Assignment-075[]
//tag::Quiz-12[]
Quiz 12

//end::Quiz-12[]
//end::Week-18[]

==== Week 19
//tag::Week-19[]
//tag::Weekly-Overview-19[]
19

//end::Weekly-Overview-19[]
//end::Week-19[]

==== Week 20
//tag::Week-20[]
//tag::Weekly-Overview-20[]
20

//end::Weekly-Overview-20[]

//tag::Assignment-076[]
===== Monday, December 2, 2024

Complete 32c by writing the word that should go in the blank. Then translate the sentence.

//end::Assignment-076[]
//tag::Assignment-077[]
===== Tuesday, December 3, 2024
*Seminar Day*

We completed 32d in class. Give the passive form of each verb.

//end::Assignment-077[]
//tag::Assignment-078[]
===== Wednesday, December 4, 2024

Complete 31b by tranlating the text. Pay attention to verb forms.

Study the vocabulary for 
https://drive.google.com/open?id=15Sbic1JNBe47X5Dfusk-tbNppIhKTpdg&usp=drive_fs[Chapter 31]
and
https://drive.google.com/file/d/15uvTXkiCoT7mx8gSwz6HuonUItohLL_X/view?usp=sharing[Chapter 32]

//end::Assignment-078[]
//tag::Assignment-079[]
===== Thursday, December 5, 2024

Submit 31b.

Study the vocabulary for 
https://drive.google.com/open?id=15Sbic1JNBe47X5Dfusk-tbNppIhKTpdg&usp=drive_fs[Chapter 31]
and
https://drive.google.com/file/d/15uvTXkiCoT7mx8gSwz6HuonUItohLL_X/view?usp=sharing[Chapter 32]

//end::Assignment-079[]
//tag::Assignment-080[]
===== Friday, December 6, 2024
//31f

//end::Assignment-080[]
//tag::Quiz-13[]
Quiz over all verb forms that we have studied. 

//end::Quiz-13[]
//end::Week-20[]

==== Week 21
//tag::Week-21[]
//tag::Weekly-Overview-21[]
21

//end::Weekly-Overview-21[]

//tag::Assignment-081[]
===== Monday, December 9, 2024

//end::Assignment-081[]
//tag::Assignment-082[]
===== Tuesday, December 10, 2024

//end::Assignment-082[]
//tag::Assignment-083[]
===== Wednesday, December 11, 2024

//end::Assignment-083[]
//tag::Assignment-084[]
===== Thursday, December 12, 2024

//end::Assignment-084[]
//tag::Assignment-085[]
===== Friday, December 13, 2024
*Last Day of School*

//end::Assignment-085[]
//tag::Test-04[]
Make sure to know the vocabulary from chapters 31 and 32, the verb charts on pages 331 and 332, how to translate the different froms of verbs, and the noun charts on page 323.

//end::Test-04[]
//end::Week-21[]







== 3rd Quarter
=== Module 5 -- Chapters 33-34
==== Week 22
//tag::Week-22[]
22

//tag::Weekly-Overview-22[]


//end::Weekly-Overview-22[]
//tag::Assignment-086[]
===== Monday, December 30, 2024
*Holiday*

//end::Assignment-086[]
//tag::Assignment-087[]
===== Tuesday, December 31, 2024
*Holiday*

//end::Assignment-087[]
//tag::Assignment-088[]
===== Wednesday, January 1, 2024
*Holiday*
 
//end::Assignment-088[]
//tag::Assignment-089[]
===== Thursday, January 2, 2024
*Satellite Day*

Translate the story on page 49.

Study https://drive.google.com/file/d/1AMXiDLSclMxwEZLLXUoAuBRgBQUet1NC/view?usp=sharing[Chapter 33 Vocabulary]

//end::Assignment-089[]
//tag::Assignment-090[]
===== Friday, January 3, 2024
*Satellite Day*

Translate the story on page 50.

Study https://drive.google.com/file/d/1AMXiDLSclMxwEZLLXUoAuBRgBQUet1NC/view?usp=sharing[Chapter 33 Vocabulary]

//end::Assignment-090[]
//end::Week-22[]



==== Week 23
//tag::Week-23[]
//tag::Weekly-Overview-23[]

We will learn about perfect passive participles. 

//end::Weekly-Overview-23[]
*Teacher Work Day*

//tag::Assignment-091[]
===== Monday, January 6, 2025
*Satellite Day*

Finish/review the translation from pages 49-50. Submit your translation.

Study https://drive.google.com/file/d/1AMXiDLSclMxwEZLLXUoAuBRgBQUet1NC/view?usp=sharing[Chapter 33 Vocabulary]

//end::Assignment-091[]
*First Day Back in Class*

//tag::Assignment-092[]
===== Tuesday, January 7, 2025

We reviewed perfect passive participles, and we worked on 33b.

//end::Assignment-092[]
//tag::Assignment-093[]
===== Wednesday, January 8, 2025

Finish 33b by writing the perfect passive participle and the noun it is modifying. Then translate the sentence. 

Study https://drive.google.com/file/d/1AMXiDLSclMxwEZLLXUoAuBRgBQUet1NC/view?usp=sharing[Chapter 33 Vocabulary]


//end::Assignment-093[]
//tag::Assignment-094[]
===== Thursday, January 9, 2025

Submit 33b.

Study https://drive.google.com/file/d/1AMXiDLSclMxwEZLLXUoAuBRgBQUet1NC/view?usp=sharing[Chapter 33 Vocabulary] and 33b.


//end::Assignment-094[]
//tag::Assignment-095[]
===== Friday, January 10, 2025

//end::Assignment-095[]
//tag::Quiz-14[]

Quiz over the vocabulary for chapter 33 and identifying perfect passive participles.

//end::Quiz-14[]
//end::Week-23[]

==== Week 24
//tag::Week-24[]
//tag::Weekly-Overview-24[]

We will continue to learn about perfect passive participles. 

//end::Weekly-Overview-24[]

//tag::Assignment-096[]
===== Monday, January 13, 2025

Study https://drive.google.com/file/d/1AMXiDLSclMxwEZLLXUoAuBRgBQUet1NC/view?usp=sharing[Chapter 33 Vocabulary] and 33b.


//end::Assignment-096[]
//tag::Assignment-097[]
===== Tuesday, January 14, 2025
We translated 33c.

//end::Assignment-097[]
//tag::Assignment-098[]
===== Wednesday, January 15, 2025
Finish translating 33c.

Review https://drive.google.com/file/d/1AMXiDLSclMxwEZLLXUoAuBRgBQUet1NC/view?usp=sharing[Chapter 33 Vocabulary] and perfect passive participles.

Be able to identify a participle, the noun it is modifying, and its gender, number, and case.

//end::Assignment-098[]
//tag::Assignment-099[]
===== Thursday, January 16, 2025
Submit the translation for 33c

Review https://drive.google.com/file/d/1AMXiDLSclMxwEZLLXUoAuBRgBQUet1NC/view?usp=sharing[Chapter 33 Vocabulary] and perfect passive participles.

Be able to identify a participle, the noun it is modifying, and its gender, number, and case.

//end::Assignment-099[]
//tag::Assignment-100[]
===== Friday, January 17, 2025

//end::Assignment-100[]
//tag::Quiz-15[]

Be able to identify a participle, the noun it is modifying, and its gender, number, and case.

//end::Quiz-15[]
//end::Week-24[]


==== Week 25
//tag::Week-25[]
Review Chapters 18-21
//tag::Weekly-Overview-25[]
25

//end::Weekly-Overview-25[]
//tag::Assignment-101[]
===== Monday, January 20, 2025
*Holiday-MLK Day*

//end::Assignment-101[]
//tag::Assignment-102[]
===== Tuesday, January 21, 2025

We reviewed the last quiz and took a bonus quiz.

//end::Assignment-102[]
//tag::Assignment-103[]
===== Wednesday, January 22, 2025

Study https://drive.google.com/file/d/1EbZn_4aEIs5GkOkcTk074KwAtp1HrAUl/view?usp=sharing[Chapter 34 Vocabulary]

Translate lines 1-12 on page 63.

//end::Assignment-103[]
//tag::Assignment-104[]
===== Thursday, January 23, 2025

Study https://drive.google.com/file/d/1EbZn_4aEIs5GkOkcTk074KwAtp1HrAUl/view?usp=sharing[Chapter 34 Vocabulary]

Submit lines 1-12 on page 63.

//end::Assignment-104[]
//tag::Assignment-105[]
===== Friday, January 24, 2025

//end::Assignment-105[]
//tag::Quiz-16[]

Quiz over https://drive.google.com/file/d/1EbZn_4aEIs5GkOkcTk074KwAtp1HrAUl/view?usp=sharing[Chapter 34 Vocabulary]

//end::Quiz-16[]
//end::Week-25[]

==== Week 26
//tag::Week-26[]
Review Chapters 22-24
//tag::Weekly-Overview-26[]
26

//end::Weekly-Overview-26[]
//tag::Assignment-106[]
===== Monday, January 27, 2025

Finish 34f

Translate lines 13-18 on page 63

Submit 34f and lines 13-18 on page 63

//end::Assignment-106[]
//tag::Assignment-107[]
===== Tuesday, January 28, 2025

//end::Assignment-107[]
//tag::Assignment-108[]
===== Wednesday, January 29, 2025

Study the endings on page 324.

//end::Assignment-108[]
//tag::Assignment-109[]
===== Thursday, January 30, 2025

Study the endings on page 324.

//end::Assignment-109[]
//tag::Assignment-110[]
===== Friday, January 31, 2025

//end::Assignment-110[]

//tag::Quiz-17[]

Quiz over noun/adjective endings.

Be able to tell the difference between positive, comparative, and superlative forms.

Be able to tell the gender, number, and case of adjectives. 


//end::Quiz-17[]
//end::Week-26[]

=== Module 6 -- Chapters 35-36
==== Week 27
//tag::Week-27[]
Review Chapters 25-27
//tag::Weekly-Overview-27[]
27

//end::Weekly-Overview-27[]
//tag::Assignment-111[]
===== Monday, February 3, 2025

Finish and submit the translation from page 59.

//end::Assignment-111[]
//tag::Assignment-112[]
===== Tuesday, February 4, 2025

//end::Assignment-112[]
//tag::Assignment-113[]
===== Wednesday, February 5, 2025

Find adjectives and participles in 34H. Give the type of adjective it is as well as the gender, number, and case.

You can also look for adjectives from earlier chapters using https://joshualbogle.com/. If you click on the word it should tell you the gender, number, and case of adjectives.

//end::Assignment-113[]
//tag::Assignment-114[]
===== Thursday, February 6, 2025

Submit the adjetives you found on 34H.

Study for your test.

//end::Assignment-114[]
//tag::Assignment-115[]
===== Friday, February 7, 2025


//end::Assignment-115[]


//tag::Test-05[]

Study the vocabulary for chapters 33 and 34, perfect passive participles, and positive, comparative, and superlative adjectives.

//end::Test-05[]



//end::Week-27[]


==== Week 28
//tag::Week-28[]
//tag::Weekly-Overview-28[]
28

//end::Weekly-Overview-28[]
//tag::Assignment-116[]
===== Monday, February 10, 2025

Look over your vocabulary for
https://drive.google.com/file/d/15eWBYNPgJQFgoJA72P2EAdAgQWEmZT4T/view?usp=sharing[Chapter 35]

//end::Assignment-116[]
//tag::Assignment-117[]
===== Tuesday, February 11, 2025

//end::Assignment-117[]
//tag::Assignment-118[]
===== Wednesday, February 12, 2025

Study https://drive.google.com/file/d/15eWBYNPgJQFgoJA72P2EAdAgQWEmZT4T/view?usp=sharing[Chapter 35]

Finish translating the story on page 71 and 72.

//end::Assignment-118[]
//tag::Assignment-119[]
===== Thursday, February 13, 2025

Study https://drive.google.com/file/d/15eWBYNPgJQFgoJA72P2EAdAgQWEmZT4T/view?usp=sharing[Chapter 35]

Submit your translation the story on page 71 and 72.

//end::Assignment-119[]
//tag::Assignment-120[]
===== Friday, February 14, 2025

//end::Assignment-120[]

//tag::Quiz-18[]

Chapter 35 Vocabulary quiz. 

//end::Quiz-18[]

//end::Week-28[]

==== Week 29
//tag::Week-29[]
//tag::Weekly-Overview-29[]
29

//end::Weekly-Overview-29[]
//tag::Assignment-121[]
===== Monday, February 17, 2025

Translate and upload 35D.

Review the differences between positive, comparative, and superlatives adjectives and positive, comparative, and superlative adverbs.

We will have a "Quiz" over adjectives and adverbs. It will replace your lowest quiz grade this quarter. 

//end::Assignment-121[]
//tag::Assignment-122[]
===== Tuesday, February 18, 2025

We will have a "Quiz" over adjectives and adverbs. It will replace your lowest quiz grade this quarter. 

//end::Assignment-122[]



//tag::Assignment-123[]
===== Wednesday, February 19, 2025

Translate 35h


//end::Assignment-123[]
//tag::Assignment-124[]
===== Thursday, February 20, 2025

Submit 35h

//end::Assignment-124[]
//tag::Assignment-125[]
===== Friday, February 21, 2025
*Winter Holiday*

//end::Assignment-125[]
//tag::Quiz-19[]
Quiz 19

//end::Quiz-19[]

//end::Week-29[]


==== Week 30
//tag::Week-30[]
//tag::Weekly-Overview-30[]
30

//end::Weekly-Overview-30[]

//tag::Assignment-126[]
===== Monday, February 24, 2025

Review the vocabulary for
https://drive.google.com/open?id=1In7EZuBXz32i64V1INtSO9OYYi4kFwpO&usp=drive_fs[Chapter 36]

//end::Assignment-126[]
//tag::Assignment-127[]
===== Tuesday, February 25, 2025
Chapel Schedule

//end::Assignment-127[]
//tag::Assignment-128[]
===== Wednesday, February 26, 2025

Complete 36b if you did not finish it in class.

Study 
https://drive.google.com/open?id=1In7EZuBXz32i64V1INtSO9OYYi4kFwpO&usp=drive_fs[Chapter 36 Vocabulary]
and Roman dates on pages 88-90.

Translate page 87.

//end::Assignment-128[]
//tag::Assignment-129[]
===== Thursday, February 27, 2025

Submit 36b and page 87.



//end::Assignment-129[]
//tag::Assignment-130[]
===== Friday, February 28, 2025

//end::Assignment-130[]
//tag::Quiz-20[]

Quiz over vocabulary and dates.

//end::Quiz-20[]
//end::Week-30[]

==== Week 31
//tag::Week-31[]
//tag::Weekly-Overview-31[]
31

//end::Weekly-Overview-31[]
//tag::Assignment-131[]
===== Monday, March 3, 2025

Finish and submit the translation to the story on page 88.

//end::Assignment-131[]
//tag::Assignment-132[]
===== Tuesday, March 4, 2025

//end::Assignment-132[]
//tag::Assignment-133[]
===== Wednesday, March 5, 2025

Study for the test over 35 and 36. Study the vocabulary for chapters 35 and 36, adjectives and adverbs, and dates.

//end::Assignment-133[]
//tag::Assignment-134[]
===== Thursday, March 6, 2025

Submit what you translated in class Tuesday.

Study for the test over 35 and 36. Study the vocabulary for chapters 35 and 36, adjectives and adverbs, and dates.

//end::Assignment-134[]
//tag::Assignment-135[]
===== Friday, March 7, 2025

End of 3rd term




//end::Assignment-135[]
//tag::Test-06[]

Test over 35 and 36. Study the vocabulary for chapters 35 and 36, adjectives and adverbs, and dates.

//end::Test-06[]
//end::Week-31[]


== 4th Quarter
=== Module 7 -- Chapters 37-38
==== Week 32
//tag::Week-32[]
//tag::Weekly-Overview-32[]
32

//end::Weekly-Overview-32[]
//tag::Assignment-136[]
===== Monday, March 10, 2025

Study https://drive.google.com/file/d/1HRwKjB-WQ6gZwi20p9t7FkS88iztBo2j/view?usp=sharing[Chapter 37 Vocabulary]

//end::Assignment-136[]
//tag::Assignment-137[]
===== Tuesday, March 11, 2025

//end::Assignment-137[]
//tag::Assignment-138[]
===== Wednesday, March 12, 2025

//end::Assignment-138[]
//tag::Assignment-139[]
===== Thursday, March 13, 2025

//end::Assignment-139[]
//tag::Assignment-140[]
===== Friday, March 14, 2025

//end::Assignment-140[]
//tag::Quiz-21[]
Quiz 21

//end::Quiz-21[]
//end::Week-32[]


==== Week 33
//tag::Week-33[]
//tag::Weekly-Overview-33[]
33

//end::Weekly-Overview-33[]

//tag::Assignment-141[]
===== Monday, March 17, 2025

//end::Assignment-141[]
//tag::Assignment-142[]
===== Tuesday, March 18, 2025
*Seminar Day*


//end::Assignment-142[]
//tag::Assignment-143[]
===== Wednesday, March 19, 2025

//end::Assignment-143[]
//tag::Assignment-144[]
===== Thursday, March 20, 2025

//end::Assignment-144[]
//tag::Assignment-145[]
===== Friday, March 21, 2025

//end::Assignment-145[]
//tag::Quiz-22[]
Quiz 22

//end::Quiz-22[]
//end::Week-33[]

==== Week 34
//tag::Week-34[]
//tag::Weekly-Overview-34[]
34

//end::Weekly-Overview-34[]

//tag::Assignment-146[]
===== Monday, March 24, 2025

//end::Assignment-146[]
//tag::Assignment-147[]
===== Tuesday, March 25, 2025

//end::Assignment-147[]
//tag::Assignment-148[]
===== Wednesday, March 26, 2025

//end::Assignment-148[]
//tag::Assignment-149[]
===== Thursday, March 27, 2025

//end::Assignment-149[]
//tag::Assignment-150[]
===== Friday, March 28, 2025

//end::Assignment-150[]
//tag::Quiz-23[]
Quiz 23

//end::Quiz-23[]
//end::Week-34[]




==== Week 35
//tag::Week-35[]
//tag::Weekly-Overview-35[]
35

//end::Weekly-Overview-35[]

//tag::Assignment-151[]
===== Monday, March 31, 2025

//end::Assignment-151[]
//tag::Assignment-152[]
===== Tuesday, April 1, 2025

//end::Assignment-152[]
//tag::Assignment-153[]
===== Wednesday, April 2, 2025

//end::Assignment-153[]
//tag::Assignment-154[]
===== Thursday, April 3, 2025

//end::Assignment-154[]
//tag::Assignment-155[]
===== Friday, April 4, 2025

//end::Assignment-155[]
//tag::Test-07[]
Test 7

//end::Test-07[]
//end::Week-35[]

=== Module 8 -- Chapter 39

==== Week 36
//tag::Week-36[]
//tag::Weekly-Overview-36[]
36

//end::Weekly-Overview-36[]
Sping Break

//end::Week-36[]

==== Week 37
//tag::Week-37[]
//tag::Weekly-Overview-37[]
37

//end::Weekly-Overview-37[]
//tag::Assignment-156[]
===== Monday, April 14, 2025

//end::Assignment-156[]
//tag::Assignment-157[]
===== Tuesday, April 15, 2025

*Seminar Day*

//end::Assignment-157[]
//tag::Assignment-158[]
===== Wednesday, April 16, 2025

//end::Assignment-158[]
//tag::Assignment-159[]
===== Thursday, April 17, 2025

//end::Assignment-159[]
//tag::Assignment-160[]
===== Friday, April 18, 2025

*Good Friday*

//end::Assignment-160[]
//tag::Quiz-24[]
Quiz 24

//end::Quiz-24[]
//end::Week-37[]

==== Week 38
//tag::Week-38[]
//tag::Weekly-Overview-38[]
38

//end::Weekly-Overview-38[]

//tag::Assignment-161[]
===== Monday, April 21, 2025

//end::Assignment-161[]
//tag::Assignment-162[]
===== Tuesday, April 22, 2025

//end::Assignment-162[]
//tag::Assignment-163[]
===== Wednesday, April 23, 2025

//end::Assignment-163[]
//tag::Assignment-164[]
===== Thursday, April 24, 2025

//end::Assignment-164[]
//tag::Assignment-165[]
===== Friday, April 25, 2025

//end::Assignment-165[]
//tag::Quiz-25[]
Quiz 25

//end::Quiz-25[]
//end::Week-38[]

==== Week 39
//tag::Week-39[]
//tag::Weekly-Overview-39[]
39

//end::Weekly-Overview-39[]

//tag::Assignment-166[]
===== Monday, April 28, 2025

//end::Assignment-166[]
//tag::Assignment-167[]
===== Tuesday, April 29, 2025

*Chapel Day*

//end::Assignment-167[]
//tag::Assignment-168[]
===== Wednesday, April 30, 2025

//end::Assignment-168[]
//tag::Assignment-169[]
===== Thursday, May 1, 2025

//end::Assignment-169[]
//tag::Assignment-170[]
===== Friday, May 2, 2025

//end::Assignment-170[]
//tag::Quiz-26[]
Quiz 26

//end::Quiz-26[]
//end::Week-39[]


==== Week 40
//tag::Week-40[]
//tag::Weekly-Overview-40[]
40

//end::Weekly-Overview-40[]

//tag::Assignment-171[]
===== Monday, May 5, 2025

//end::Assignment-171[]
//tag::Assignment-172[]
===== Tuesday, May 6, 2025
*Last full day in class*

//end::Assignment-172[]
//tag::Assignment-173[]
===== Wednesday, May 7, 2025

//end::Assignment-173[]
//tag::Assignment-174[]
===== Thursday, May 8, 2025

//end::Assignment-174[]
//tag::Assignment-175[]
===== Friday, May 9, 2025
*1/2 day of testing*

//end::Assignment-175[]
//tag::Quiz-27[]
Quiz 27

//end::Quiz-27[]
//end::Week-40[]

==== Week 41
//tag::Week-41[]
//tag::Weekly-Overview-41[]
41

//end::Weekly-Overview-41[]

//tag::Assignment-176[]
===== Monday, May 12, 2025

//end::Assignment-176[]
//tag::Assignment-177[]
===== Tuesday, May 13, 2025
*1/2 day of testing*

*Final Day of School*

//end::Assignment-177[]


//tag::Test-08[]
Test 8

//end::Test-08[]


//tag::Assignment-178[]
===== Wednesday, May 14, 2025

//end::Assignment-178[]
//tag::Assignment-179[]
===== Thursday, May 15, 2025

//end::Assignment-179[]
//tag::Assignment-180[]
===== Friday, May 16, 2025

*Teacher work day*

//end::Assignment-180[]

//end::Week-41[]