//tag::Story[] 
== *Chapter 17 – Reading Latin – Aurelia is Worried, but Sextus is Not*

Dum Cornēliī per viam ad caupōnam ībant, Aurēlia sollicita erat. 
"Ego pernoctāre in caupōnā nōlō," inquit māter misera, "quod caupōnae semper sunt perīculōsae. 
Saepe praedōnēs scelestī in cauōnīs pernoctant."

Sextus, quī ad caupōnam īre volēbat, "Fortasse," inquit, "praedōnēs scelestī in caupōnā nostrā sunt! Praedōnēs vidēre volō." 
Nunc Cornēlia misera lacrimābat quod praedōnēs timēbat.

"Tacē, Sexte! Nōlumus fēminās terrēre," inquit Mārcus. 
Sextus, "Nōlī,"inquit, "mē vexāre, Mārce! 
Omnēs praedōnēs pūgiōnēs et magna bacula sēcum ferunt sed nōs nōn ferimus. 
Ēheu! Negue baculum neque pūgiōnem ferō sed pilam tantum habeō. 
Fertne Cornēlius pūgiōnem?"

"Tempus est tacēre, moleste!" inquit Cornēlius, īrā commōtus. 
"Vīsne terrēre. Aurēliam et Cornēliam?"

"Cūr Aurēlia et Cornēlia perterritae sunt?" rogābat puer fatuus.

Nēmō respondēre poterat sed omnēs ad caupōnam celeriter ībant quod advesperāscēbat. 
Brevī tempore Sextus laetus, "Syrus," inquit, "virgam habet. 
Praedōnēs virgā Syrī feriam. 
Syre, ubi es? "Syrus, inquit Cornēlius, "a raedam manet." 
Sextus nōn iam laetus erat.
//end::Story[] 

=== *Vocabulary*

- praedō, praedōnis, m., robber

- pūgiō, pūgiōnis, m., knife, dagger

- sēcum, with them

- feriam, I will hit

=== *Questions*

need scan
