//tag::Story[] 
== *Chapter 22 – Reading Latin – Titus Gets Ready*

In urbe Rōmā diēs iam calidus erat. Servī et ancillae Titī cibum coquēbant, domum pūrgābant, tacitē labōrābant quod dominum excitāre nōlēbant. Titus tamen in lectō iacēbat et stertēbat, immemor frātris Cornēliī.

Tandem servus Titī cubiculum intrāvit et dominum excitāvit. Titus invītus surrēxit et, “Fer ad mē cibum et tunicam pūram,” servō clāmāvit. Brevī tempore servus tunicam et cibum ad dominum tulit. Dum auxiliō servī tunicam induit, Titus rogāvit, “Quota hōra est?”

“Est quīnta hōra, domine,” respondit servus. “Nōndum est tempus cēnāre.” Eō ipsō tempore alius servus Titī ad iānuam appāruit. “Est nūntius in ātriō, mī domine,” inquit. “Epistulam tibi habet,”

“Mehercule! Habetne mihi espistulam? Statim eum vocā,” exclāmāvit Titus. Brevī tempore intrāvit nūntius quī epistulam Titō trādidit. Titus epistulam lēgit. “Ēheu!” exclāmāvit Titus. “Necesse est mihi lectīcāriōs statim condūcere et frātrem et familiam eius ad Portam Capēnam excipere. Cūr mē nōn prius excitāvistī?”

“Frātrem et familiam iterum excipis? Nōnne heri ad urbem advēnērunt?” rogāvit servus.

“Minimē,” respondit Titus. “Heri lectīcāriōs condūxī et ad Portam Capēnam iī. Multās hōrās ibi manēbam, sed frāter meus numquam advēnit. Tandem domum rediī. Haec epistula rem explicat. Cornēlius aliquid malī accēpit et familia in caupōnā pernoctāvit. Nunc omnēs iterum in itinere sunt; Cornēlius ad Portam Capēnam sexā hōrā advenīre vult. Ī statim ad Forum! Celeriter meō frātrī Cornēliō et Aurēliae et Cornēliae condūc lectīcāriōs! Aliī lectīcāriī mē ad portam Capēnam ferent.”

Celeriter servī omnia Titō parāvērunt. “Quam dēfessus sum!” exclāmāvit Titus.
//end::Story[] 

=== Vocabulary 

domum, house, home

stertō, stertere, stertuī, to snore

pūrus, -a, -um, clean

ātrium, -ī, n., atrium, main room

lectīcārius, -ī, m., litter-bearer

condūcō, condūcere, condūxī, conductus, to hire

familia, -ae, f., family, household

eius, his

prius, adv., earlier

aliquid malī, something bad

accipiō, accipere, accēpī, acceptus, to receive

ferent, will carry

=== Questions

Cui surgere māne nōn necesse fuit?

Cui Titus clāmāvit?

Cui nūntius epistulam trādidit?

Quibus Titus lectīcāriōs condūcere voluit?

Quibus Titus exclāmāvit "Quam dēfessus sum!"?