//tag::Story[] 
== *Chapter 27 – Reading Latin – More News for Flavia from Cornelia*

Mē et puerōs ad lūdōs in Circō Maximō factōs heri Eucleidēs dūxit. Ubi ē somnō surrēxī, puerī et Eucleidēs sē iam parāverant. Statim igitur Circum petīvimus. Ubi eō pervēnimus, patruus noster cum suīs amīcīs iam prope curriculum cōnsēderat. Quamquam prope curriculum sedēre nōbīs nōn licuit, omnia tamen vidēre potuimus. Postquam aurīgae eōs ferōciter verberābant!

Omnēs mulierēs, senātōrēs, cīvēs, servī factiōnibus suīs strēnuē favēbant. Quam magnae erant vōcēs eōrum! Ego et puerī factiōnibus nostrīs favēbāmus. Sextus, ille puer molestus, nōbīs identidem clāmābat, “Meī russātī semper vestrōs aurīgās vincent!” Quamquam prīmō russātī eius vīcērunt meī venetī saepe vīcērunt. Albātī Mārcī nōn bene currēbant, et Mārcus miser sibi mussābat. Pauca post certāmina tempus fuit discēdere. Dum domum redībāmus, puerī mē vexāre temptābant, ut semper, sed eōs vītāre poteram.

Cum tū ad urbem vēneris, nōbīscum ad lūdōs circēnsēs fortasse īre poteris! Licēbitne mox tibi Rōmam venire? Sī māter tua tēcum vēnerit, laeta erit māter mea quod eam vidēre vult.

Necesse est mihi cubitum īre. Valē, mea amīca.
//tag::Story[] 

=== *Vocabulary*
- prīmō, adv., at first
- paucī, -ae, -a, a few
- certāmen, certāminis, n., contest

=== *Questions*
. Postquam Mārcus et Sextus sē quiētī dedērunt, puerī et Cornēlia cum Eucleide Circum perīvērunt.   V   F

. Mārcus et Cornēlia patruum suum cum amīcīs eius sedentem in Circō cōnspexērunt.   V   F

. Omnēs factiōnibus suīs favēbant.  V   F

. Mārcus erat miser et Sextō mussābat.  V   F

. Dum līberī domum redībant, Cornēlia puerōs molestōs vītābat.  V   F

. Cornēliae māter mātrem Flāviae vidēre vult    V   F
