= *Reading Latin*

== *In the Kitchen*

Postquam Cornēlia et Aurēlia in sellīs discessērunt, Elissa, ancilla nova, cum aliīs ancillīs in culīnā strēnuē labōrābat.

Syra:   Ubi tū antehāc habitāvistī, Elissa?

Elissa: Habitābam apud familiam, cuius vīlla extrā urbem in collibus est. 
Ēheu! Vīlla nostra erat magna, sed nōn erant multī servī. 
Cotīdiē strenuē labōrāre necesse erat. quam miserī erāmus!

Syra:   Quam fēlix nunc es! Certē domus Cornēliī magna est, sed dominus noster multōs servōs et multās ancillās habet. 
Cūrāmus bonam familiam, quae nūper ad urbem subitō rediit.

Anna:   Habēmus duōs strenuōs puerōs, Mārcum et Sextum, quibus multum cibum parāmus quod semper ēsuriunt! 
Mārcus est fīlius dominī nostrī et puer optimus.

Elissa: Quis est Sextus?

Anna:   Pater Sextī, quem prīnceps ad Asiam mīsit, est hospes Cornēliī. 
Sextus igitur cum familiā nostrā manet. 
Sunt in urbe multa quae Sextus numquam anteā vīdit.

Elissa: Quid est nōmen fīliae, quam in sellā vīdī? 
Cūr cum mātre suā discessit?

Anna:   Corēnlia est fīlia Aurēliae, quācum ad tabernās iit. 
Glīrēs et multa alia ement.

Elissa: Quam ob causam glīrēs ement?
Quam ob causam tantus strepitus in domō est?
Cūr omnēs strēnuē labōrāmus?

(Subitō īntrāvit Phrygia sollicita, quae omnia audīverat.)

Phrygia:    Cornēlius, dominus noster habet amīcōs, quōs ad cēnam invītāvit.
Tribus diēbus convīvae advenient.
Nōbīs igitur cibum coquere et domum parāre necesse est. Ātrium pūrgāre vōbīs necesse est, Syra et Elissa.
Holera parāre tibi necesse est, Anna.
Vestra neglegentia dominam valdē vexābit.
Agite, ignāvae ancillae!
Tempus est strēnuē labōrāre!

=== *Vocabulary*

- antehāc, adv., previously

- collis, collis, m., hill

- fēlīx, fēlīcis, happy, lucky

- nūper, adv., recently

- emō, emere, ēmī, ēmptus, to buy

- convīva, -ae, m., guest

- holus, holeris, n., vegetable

=== *Questions*

. Elissa extrā urbem in collibus habitābat.   V   F

. Cornēliī habitant in domō in quā nōn sunt multī servī et multae ancillae.    V   F

. Ancillae cūrant Cornēliōs quī ad urbem nūper rediērunt.   V   F

. Puerī multum cibum ancillīs parant.   V   F

. Prīnceps Cornēlium ad Asiam mīsit.  V   F

. Nōmen puellae quae in sellā discessit Cornēlia est.   V   F

. Syra et elissa holera parābunt; Anna ātrium pūrgābit. V   F
