= *Reading Latin Chapter 29*

== *What's Going on Here?*

Mārcus: Quem in tablīnō patris audīvī? 
Quis es?
Esne servus?
Quam ob causam in tablīnō es?

Sextus: (quī in peristȳlium rumpit) Salvē, Mārce!
Mē cēlābam quod Eucleidēs mē petēbat. 
Ēheu! Librī quīdam patris utī in solum cecidērunt! 
(Puerī ad ātrium appropinquant.)
Quam occupātī sunt servī!
Cūr hūc illūc festīnant?
Quid accidit?

Mārcus: Servī strēnuē labōrant quod pater meus complūrēs ad cēnam invītāvit.
Cēnam ēlegantissimam et ingentem parābit coquus noster.
Hodiē igitur servī et ancillae domum pūrgant.

Sextus: Quōs invītāvit pater tuus?

Mārcus: Invītāvit pater senātōrēs quōsdam et clientēs, quī ab omnibus partibus urbis ad domum nostram venient.

Sextus: Quōs senātōrēs ad hanc cēnam invītāvit?
Quī convīvae hīc cēnābunt?

Mārcus: Senātōrēs quī sunt amīcī eius invītāvit.
Etiam apud nōs cēnābunt senātōrēs quī patrem meum ad cēnam invīvāvērunt.
Certē Titus, patruus meus, quoque aderit.
Quōrum vōcēs audīmus?

Sextus: Audīmus ancillārum quārundam quae trīclīnium et ātrium pūrgant.

Mārcus: Mox afferent ad trīclīnium ancdēlābra et ōrnāmenta et lectōs, in quibus convīvae recumbere solent dum cēnant.

Sextus: Quibuscum illā nocte cēnābimus ego et tū?
Cum senātōribus, cum clientibus? 
Ego sum fīlius senātōris praeclārī!

Mārcus: (cum rīsū) Ēheu! Cum Cornēliā cēnābimus, nam puerī sumus, nōn senātōrēs.

=== *Vocabulary*

- solum, -ī, n., floor

- complūrēs, -ēs, -a, several, many

- coquus, -ī, m., cook

- candēlābrum, -ī, n., candelabrum, lamp-stand

- ōrnāmenta, -ōrum, n., furnishings

- convīva, -ae, m., guest (at a banquet)

=== *Questions*

. Quem in tablīnō audīvit Mārcus?

. Ā quō fugit Sextus?

. Quibuscum Cornēlius cēnābit?

. Cuius amicōs invītāvit Cornēlius?

. Quem quoque invītāvit Cornēlius?

. in quibus convīvae recumbunt dum cēnant?

. Quid ad trīclīnium portābunt servī quīdam?